name: "Close stale issues and PRs"

on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v4.0.0
        with:
          stale-issue-message: 'This issue had no activity for **6 months**. It will be closed in **2 weeks** unless there is some new activity. Is this issue already resolved?'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,enhancement,good first issue'
          stale-pr-message: 'This pull request had no activity for **6 months**. It will be closed in **2 weeks** unless there is some new activity.'
          stale-pr-label: 'stale'
          days-before-stale: 180
          days-before-close: 14
          operations-per-run: 200
